{
  "formatVersion": "1.1",
  "component": {
    "group": "com.neutrondrive",
    "module": "NeutronDrive",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "NeutronDrive-1.0.0.jar",
          "url": "NeutronDrive-1.0.0.jar",
          "size": 31286,
          "sha512": "f25f741b1ce2afc6ab2fb0fae5e4c9c30ccba783c6c1ab504b3344ba4df9e4bafee52672454f67b11a6376d29640a17e0b119c4fc0e5488eb92a45bfb430d1be",
          "sha256": "3862a0a7bd2556396a644b5764f095ebefca9a0b12c870c8861dfbf34fa08841",
          "sha1": "947a1cf8df5aef272590da382691bdc5bed6925e",
          "md5": "2153b8d6864d566cbf1281a4872df32c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiunits",
          "module": "wpiunits-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2026.2.1"
          }
        },
        {
          "group": "com.ctre.phoenix6",
          "module": "wpiapi-java",
          "version": {
            "requires": "26.1.1"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2026.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "NeutronDrive-1.0.0.jar",
          "url": "NeutronDrive-1.0.0.jar",
          "size": 31286,
          "sha512": "f25f741b1ce2afc6ab2fb0fae5e4c9c30ccba783c6c1ab504b3344ba4df9e4bafee52672454f67b11a6376d29640a17e0b119c4fc0e5488eb92a45bfb430d1be",
          "sha256": "3862a0a7bd2556396a644b5764f095ebefca9a0b12c870c8861dfbf34fa08841",
          "sha1": "947a1cf8df5aef272590da382691bdc5bed6925e",
          "md5": "2153b8d6864d566cbf1281a4872df32c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NeutronDrive-1.0.0-sources.jar",
          "url": "NeutronDrive-1.0.0-sources.jar",
          "size": 16285,
          "sha512": "643c5960029f3f1e5cc4b0b2093d679091bc84c719dab13c391e57894e56632f5c4eb71e97318dea2450d1974d60aafdcf0c21a9ad80a4d874ebc9f46217a895",
          "sha256": "e00f43868b3877e87a204786e95b5e07e40726c447159e317e18c0b4b409f9af",
          "sha1": "c6e914b5e380995dc4fbf57c37733507dbf729bc",
          "md5": "82240dd2f4da496c5949095b619605e1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NeutronDrive-1.0.0-javadoc.jar",
          "url": "NeutronDrive-1.0.0-javadoc.jar",
          "size": 165217,
          "sha512": "d1bf093c261d27e29e3814be84598e7de994e0b341eb0d1a0df144b4809acbcd02dba6c7a91679e80f49dea955404b810ad40dbd40164e4b6f16d48832898df8",
          "sha256": "4224a7be72c1f4313dd3951e195a01ab1245aad3d41aed147fec98eef6d532fa",
          "sha1": "7612abed1de07fa0c38526b86d95d440a642aea1",
          "md5": "de8f151908cefd125813336133e15994"
        }
      ]
    }
  ]
}
